### ISSUE TITLE
About the scale of width

### ISSUE THREAD

**Issue by cyrilli** [dougsm/ggcnn_kinova_grasping#1]
https://github.com/dougsm/ggcnn_kinova_grasping/blob/06cc26eaec11a3867f5ff07efe46cdc7b8f10679/ggcnn_kinova_grasping/scripts/run_ggcnn.py#L157

Hi, thank you for sharing your code. I have been tinkering with your ggcnn for a few days and trained a few variants. I tested them on a Baxter Simulator in Gazebo and used a custom pick place pipeline. 

I have a question about how the scale of width is dealt with here though. The input of the network is a 300*300 image resized from a 400*400 image. I can see that you have transformed the grasp point for this cropping and resizing, but it seems the width hasn't been resized accordingly, for example being multiplied by 400.0/300.0 because the output width corresponds to the 300*300 image.

**Comment by manuelli** [comment]
Hi,
I noticed the same thing. To convert the width back to original image coordinates (640 x 480) we should scale it by `400/300` correct?

**Comment by dougsm** [comment]
Hey @cyrilli and @manuelli 
Yeah, you're right. Thanks for pointing that out.  I'll make sure it gets updated.

**Comment by cyrilli** [comment]
Thank you! I will close this issue then.
