### ISSUE TITLE
ROSInitException: time is not initialized,Exception AttributeError: "TransformListener instance has no attribute 'tf_sub'" 

### ISSUE THREAD

**Issue by Assets01** [dougsm/ggcnn_kinova_grasping#11]
Hello! I use the kinova_j2s7s300 to reproduce the experiment, and encounter the following error when run the kinova_open_loop_grasp.py:

rospy.exceptions.ROSInitException: time is not initialized. Have you called init_node()?
Exception AttributeError: "TransformListener instance has no attribute 'tf_sub'" in <bound method TransformListener.__del__ of <tf2_ros.transform_listener.TransformListener instance at 0x7fc27fa29ef0>> ignored

After  reconneting the robot, the problem still exists. I run the kinova_robot.launch,wrist_camera.launch and kinova_open_loop_grasp.py in the system environment (ubuntu16.04, python2.7) and run run_ggcnn.py in the anaconda virtual environment created for the implement of tensorflow. Do you have other suggestions for solving the problem?

**Comment by dougsm** [comment]
Hey @Assets01 

looks like something changed in TF that broke this old code.  I pushed a quick change that should fix it so that the TF buffer is initialised after the node.  I'm not in a position to test this at the moment so let me know if this doesn't work.

**Comment by Assets01** [comment]
> Hey @Assets01
> 
> looks like something changed in TF that broke this old code. I pushed a quick change that should fix it so that the TF buffer is initialised after the node. I'm not in a position to test this at the moment so let me know if this doesn't work.

Hi!, sorry for taking so long to reply, I will try it and reply as soon as possible.
