### ISSUE TITLE
Sigmoid instead of ** 2 for run_ggcnn.points_out?

### ISSUE THREAD

**Issue by thomascent** [dougsm/ggcnn_kinova_grasping#2]
Hi @dougsm,

First off, this is a great codebase, thanks for sharing!

I had a question regarding this line in the run_ggcnn.py script:

https://github.com/dougsm/ggcnn_kinova_grasping/blob/f84b8ff13297af781c52e54c4bf7e2b46ddc5117/ggcnn_kinova_grasping/scripts/run_ggcnn.py#L121

I've noticed that the ggcnn network can output negative affordance (which makes sense since the activation on the pos_output layer is linear). By squaring the output of the model here, doesn't this cause areas with really low (negative) affordance to seem positive? 

Would something like a sigmoid function be better here, or am I misunderstanding soemthing?

**Comment by dougsm** [comment]
G'day @thomascent 
That's a bit weird. You're absolutely right.  Looking at it, I think that line is just a relic from some older code that managed to sneak in when I made the cleaned up version of this repo. It doesn't seem to serve any purpose (except mess up some of the values as you said), so I've just deleted it.
