### ISSUE TITLE
something about simulation and real-world

### ISSUE THREAD

**Issue by jinhuan-hit** [dougsm/ggcnn_kinova_grasping#3]
Hi，I am vrey interested in your ggcnn.However，I do not have a real robot or camera.Could you please tell me how to do some simulations in Gazebo or input the depth image，output the three images？

**Comment by dougsm** [comment]
Hello,
The GG-CNN doesn't really need a robot if all you want to do is run it. It can be run on just a numpy array with depth information (e.g. from Cornell or Jacqard dataset) by just loading the model and running a forward pass. For example: https://github.com/dougsm/ggcnn/blob/master/evaluate.py#L159 

I don't know much about simulation in Gazebo, but it looks like it's possible to simulate a depth camera (http://gazebosim.org/tutorials?tut=ros_depth_camera&cat=connect_ros), but I don't know about the quality or how well the network would work.  You could possibly integrate this with a simulated version of the kinova (https://github.com/Kinovarobotics/kinova-ros/tree/master/kinova_gazebo)

It's also possible and fairly simple to simulate depth images in pybullet with loaded object meshes and pass these to the network (https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#heading=h.2ye70wns7io3, see `getCameraImage`)

Hope that helps.

**Comment by jinhuan-hit** [comment]
Thanks a lot.I will try it.

**Comment by yang-files** [comment]
Hello, dougsm. It seems that there is no evaluate.py file in it. Did you mean the eval_ggcnn.py or evaluation.py?
