### ISSUE TITLE
The question about kinova_closed_loop_grasp.py

### ISSUE THREAD

**Issue by TFLQW** [dougsm/ggcnn_kinova_grasping#5]
Thanks for your contribution. But i still have some questions about the code in kinova_closed_loop_grasp.py. On 260 line i cannot find the file of the service : kinova_msgs.srv.StartRequest()  in the kinova_ros. Could you explain that.

**Comment by dougsm** [comment]
Hi there,
The relevant service message is here: https://github.com/Kinovarobotics/kinova-ros/blob/master/kinova_msgs/srv/Start.srv

**Comment by TFLQW** [comment]
ok, I get it! Thanks.
