### ISSUE TITLE
The ValueError: Attempted relative import in non-package problem

### ISSUE THREAD

**Issue by TFLQW** [dougsm/ggcnn_kinova_grasping#6]
I have found an error the when t run the "rosrun ggcnn_kinova_grasping kinova_closed_loop_grasp.py  " the terminal pop up the "The ValueError: Attempted relative import in non-package problem" on "from .helpers.transforms import current_robot_pose, publish_tf_quaterion_as_transform, convert_pose, publish_pose_as_transform", I search on the internet if change this to "from helpers.transforms import current_robot_pose, publish_tf_quaterion_as_transform, convert_pose, publish_pose_as_transform", maybe the Relative and absolute import problem. I want to make sure i'm correct.

**Comment by dougsm** [comment]
Hello,
I'm not sure I understand.  The line you reference (https://github.com/dougsm/ggcnn_kinova_grasping/blob/004139fedd5ad304f36de76b43466b4474b2081b/ggcnn_kinova_grasping/scripts/kinova_closed_loop_grasp.py#L13) is already in the form `from helpers.transforms import ...`

**Comment by TFLQW** [comment]
@dougsm 
Thanks for your prompt answer, I guess I downloaded the previous version of this code. I will close this issue
