### ISSUE TITLE
The problem of wrist_camera.launch

### ISSUE THREAD

**Issue by TFLQW** [dougsm/ggcnn_kinova_grasping#7]
<node pkg="tf" type="static_transform_publisher" name="realsense_link_broadcaster"
        args="**0.05425 -0.024 -0.1258 3.14 1.32 0 /m1n6s200_link_6 /camera_link 10" />
How did you measure the bias between the camera_link and m1n6s200_link_6.

**Comment by TFLQW** [comment]
The code is<node pkg="tf" type="static_transform_publisher" name="realsense_link_broadcaster"   args="0.05425 -0.024 -0.1258 3.14 1.32 0 /m1n6s200_link_6 /camera_link 10" />

**Comment by TFLQW** [comment]
the code is node pkg="tf" type="static_transform_publisher" name="realsense_link_broadcaster"
        args="0.05425 -0.024 -0.1258 3.14 1.32 0 /m1n6s200_link_6 /camera_link 10"

**Comment by dougsm** [comment]
I measured the transform in CAD (with some help from the realsense datasheet).  That transform is specific to the Kinova Mico, the Realsense SR300 and the camera mount in the cad folder.

**Comment by TFLQW** [comment]
@dougsm Thanks for your answer, i will try the hand eye calibration to find out the transform between the arm and eye, but i am not sure it will work.
