### ISSUE TITLE
The problem of stack object grasp

### ISSUE THREAD

**Issue by TFLQW** [dougsm/ggcnn_kinova_grasping#8]
Thanks for all the problems that you answered previously.
I have another one about the stack objects grasping in the video, how did you achieve the segment the object you want to grasp from the stack objects. I find the code in this package can only grasp one object not in the stack, what is your solution on this problem.

**Comment by dougsm** [comment]
The system in that video does not pick a specific target object, but rather just grasps at the best calculated point in the scene, with no knowledge of objects.  If you want to pick specific objects, it would be fairly simple to mask the GG-CNN output with the output from a separate segmentation network.

**Comment by TFLQW** [comment]
Thanks for your advice, I will try it.

**Comment by TFLQW** [comment]
@dougsm Thanks for your advice, I will try it.
