### ISSUE TITLE
The question about connect the kinova

### ISSUE THREAD

**Issue by TFLQW** [dougsm/ggcnn_kinova_grasping#9]
after i have connect the kinova_j2s7s300,the terminal pose this problem could you konw what's wrong
raise rospy.exceptions.ROSInitException("time is not initialized. Have you called init_node()?")
rospy.exceptions.ROSInitException: time is not initialized. Have you called init_node()?
Exception AttributeError: "TransformListener instance has no attribute 'tf_sub'" in <bound method TransformListener.__del__ of <tf2_ros.transform_listener.TransformListener instance at 0x7f11ac83a0e0>> ignored

**Comment by TFLQW** [comment]
i run the file kinova_open_loop_grasp.py

**Comment by TFLQW** [comment]
And i alse could not set the desire position to robot because the /pose_action/tool_pose i cannot is pose the problem the cartesian action timed-out

**Comment by TFLQW** [comment]
And i alse could not set the desire position to robot because the /pose_action/tool_pose, and pose the problem "the cartesian action timed-out"

**Comment by HongminWu** [comment]
> after i have connect the kinova_j2s7s300,the terminal pose this problem could you konw what's wrong
> raise rospy.exceptions.ROSInitException("time is not initialized. Have you called init_node()?")
> rospy.exceptions.ROSInitException: time is not initialized. Have you called init_node()?
> Exception AttributeError: "TransformListener instance has no attribute 'tf_sub'" in <bound method TransformListener.**del** of <tf2_ros.transform_listener.TransformListener instance at 0x7f11ac83a0e0>> ignored

Did you  solve this problem?

**Comment by TFLQW** [comment]
@HongminWu Yeah! I think your usb port may be loose, I solved this problem by reconnecting the robot.

**Comment by HongminWu** [comment]
Thanks for  your reply. I also solved this problem.

**Comment by Assets01** [comment]
> @HongminWu Yeah! I think your usb port may be loose, I solved this problem by reconnecting the robot.

Hello! I also use the  kinova_j2s7s300 to reproduce the experiment, and encounter the same error with you, after I reconneting the robot, the problem still exists. I run the kinova_robot.launch,wrist_camera.launch and kinova_open_loop_grasp.py in the system environment (ubuntu16.04, python2.7) and run run_ggcnn.py in the anaconda virtual environment created for the implement of tensorflow. Do you have other suggestions for solving the problem?

**Comment by Assets01** [comment]
> Thanks for your reply. I also solved this problem.

Hello! I also use the kinova_j2s7s300 to reproduce the experiment, and encounter the same error with you, after I reconneting the robot, the problem still exists. I run the kinova_robot.launch,wrist_camera.launch and kinova_open_loop_grasp.py in the system environment (ubuntu16.04, python2.7) and run run_ggcnn.py in the anaconda virtual environment created for the implement of tensorflow. Do you have other suggestions for solving the problem?
